apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway

spec:
  replicas: 2
  selector:
    matchLabels:
      app: gatway
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: lamiavu/gateway
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: gatway-configmap
            - secretRef:
                name: gateway-secret
